// Stations list (deduplicated)
export const STATIONS = [
  "Helwan",
  "Ain Helwan",
  "Helwan University",
  "Wadi Hof",
  "Hadayek Helwan",
  "Maasara",
  "Tora El-Asmant",
  "Koatsika",
  "Tora El-Balad",
  "Thakanat El-Maadi",
  "Maadi",
  "Hadayek El-Maadi",
  "Dar El-Salam",
  "El-Zahraa",
  "Mar Girgis",
  "El-Malek El-Saleh",
  "Sayyeda Zeinab",
  "Saad Zaghloul",
  "Sadat",
  "Gamal Abdel Nasser",
  "Ahmed Oraby",
  "El-Shohadaa",
  "Ghamra",
  "El-Demerdash",
  "Manshiet El-Sadr",
  "Kobri El-Qobba",
  "Hammamat El-Qobba",
  "Saray El-Qobba",
  "Hadayek El-Zaitoun",
  "Helmeyet El-Zaitoun",
  "El-Matareya",
  "Ain Shams",
  "Ezbet El-Nakhl",
  "El-Marg",
  "El-Marg El-Gedida",
  "El-Munib",
  "Sakiat Mekki",
  "Dawahi El-Giza (Om El-Masryeen)",
  "El-Giza",
  "Faisal",
  "Cairo University",
  "El-Bohoth",
  "El-Dokki",
  "El-Opra",
  "Mohamed Naguib",
  "El-Attaba",
  "Misr",
  "Rawd El-Farag",
  "St. Teresa",
  "El-Khalafawy",
  "El-Mazalat",
  "Faculty of Agriculture",
  "Shubra El-Kheima",
  "Bab El-Shaariya",
  "El-Geish",
  "Abdo Basha",
  "El-Abbassiya",
  "Ardh El-Ma'ared",
  "El-Stad",
  "Kulliyat El-Banat",
  "El-Ahram",
  "Maspero",
  "Safaa Hegazy",
  "El-Kit Kat",
  "El-Sudan",
  "Embaba",
  "El-Qawmiya",
  "Wadi El-Nil",
  "Arab League",
  "Bulaq El-Dakrour",
  "Cairo Stadium",
  "Hesham Barakat",
  "Al-Azhar University",
  "Hayy El-Sabea",
  "Field Marshal Ahmed Ismail",
  "Jehan El-Sadat",
  "Field Marshal Tantawi",
  "One Ninety",
  "Air Hospital",
  "Al-Narges",
  "Al-Mustathmireen",
  "Lotus Station",
  "Golden Square",
  "Bayt Al-Watan",
  "Al-Fattah Al-Aleem Mosque",
  "District R1",
  "District R2",
  "Financial and Business District",
  "City of Arts and Culture",
  "Governmental District",
  "Misr Mosque",
  "City of Justice",
  "Adly Mansour",
  "Al-Obour",
  "Al-Mostakbal",
  "Al-Shorouk",
  "New Heliopolis",
  "Badr",
  "Al-Robiky",
  "Hadayek Al-Asema",
  "Capital Airport",
  "Arts and Culture",
  "Industrial Zone",
  "Knowledge City",
  "Cathedral of the Nativity of Christ",
  "Strategic Command",
  "International Sports City",
  "Central Capital",
];

// Arabic translation for each station
export const STATIONS_AR = {
  Helwan: "حلوان",
  "Ain Helwan": "عين حلوان",
  "Helwan University": "جامعة حلوان",
  "Wadi Hof": "وادي حوف",
  "Hadayek Helwan": "حدائق حلوان",
  Maasara: "المعصرة",
  "Tora El-Asmant": "طرة الأسمنت",
  Koatsika: "كوتسيكا",
  "Tora El-Balad": "طرة البلد",
  "Thakanat El-Maadi": "ثكنات المعادي",
  Maadi: "المعادي",
  "Hadayek El-Maadi": "حدائق المعادي",
  "Dar El-Salam": "دار السلام",
  "El-Zahraa": "الزهراء",
  "Mar Girgis": "مار جرجس",
  "El-Malek El-Saleh": "الملك الصالح",
  "Sayyeda Zeinab": "السيدة زينب",
  "Saad Zaghloul": "سعد زغلول",
  Sadat: "السادات",
  "Gamal Abdel Nasser": "جمال عبد الناصر",
  "Ahmed Oraby": "أحمد عرابي",
  "El-Shohadaa": "الشهداء",
  Ghamra: "غمرة",
  "El-Demerdash": "الدمرداش",
  "Manshiet El-Sadr": "منشية الصدر",
  "Kobri El-Qobba": "كوبري القبة",
  "Hammamat El-Qobba": "حمامات القبة",
  "Saray El-Qobba": "سراي القبة",
  "Hadayek El-Zaitoun": "حدائق الزيتون",
  "Helmeyet El-Zaitoun": "حلمية الزيتون",
  "El-Matareya": "المطرية",
  "Ain Shams": "عين شمس",
  "Ezbet El-Nakhl": "عزبة النخل",
  "El-Marg": "المرج",
  "El-Marg El-Gedida": "المرج الجديدة",
  "El-Munib": "المنيب",
  "Sakiat Mekki": "ساقية مكي",
  "Dawahi El-Giza (Om El-Masryeen)": "ضواحي الجيزة (أم المصريين)",
  "El-Giza": "الجيزة",
  Faisal: "فيصل",
  "Cairo University": "جامعة القاهرة",
  "El-Bohoth": "البحوث",
  "El-Dokki": "الدقي",
  "El-Opra": "الأوبرا",
  "Mohamed Naguib": "محمد نجيب",
  "El-Attaba": "العتبة",
  Misr: "مصر",
  "Rawd El-Farag": "روض الفرج",
  "St. Teresa": "سانت تريزا",
  "El-Khalafawy": "الخلفاوي",
  "El-Mazalat": "المظلات",
  "Faculty of Agriculture": "كلية الزراعة",
  "Shubra El-Kheima": "شبرا الخيمة",
  "Bab El-Shaariya": "باب الشعرية",
  "El-Geish": "الجيش",
  "Abdo Basha": "عبده باشا",
  "El-Abbassiya": "العباسية",
  "Ardh El-Ma'ared": "أرض المعارض",
  "El-Stad": "الاستاد",
  "Kulliyat El-Banat": "كلية البنات",
  "El-Ahram": "الأهرام",
  Maspero: "ماسبيرو",
  "Safaa Hegazy": "صفاء حجازي",
  "El-Kit Kat": "الكت كات",
  "El-Sudan": "السودان",
  Embaba: "إمبابة",
  "El-Qawmiya": "القومية",
  "Wadi El-Nil": "وادي النيل",
  "Arab League": "جامعة الدول العربية",
  "Bulaq El-Dakrour": "بولاق الدكرور",
  "Cairo Stadium": "استاد القاهرة",
  "Hesham Barakat": "هشام بركات",
  "Al-Azhar University": "جامعة الأزهر",
  "Hayy El-Sabea": "الحي السابع",
  "Field Marshal Ahmed Ismail": "المشير أحمد إسماعيل",
  "Jehan El-Sadat": "جهان السادات",
  "Field Marshal Tantawi": "المشير طنطاوي",
  "One Ninety": "التسعين",
  "Air Hospital": "المستشفى الجوي",
  "Al-Narges": "النرجس",
  "Al-Mustathmireen": "المستثمرين",
  "Lotus Station": "محطة اللوتس",
  "Golden Square": "الساحة الذهبية",
  "Bayt Al-Watan": "بيت الوطن",
  "Al-Fattah Al-Aleem Mosque": "مسجد الفتاح العليم",
  "District R1": "الحي R1",
  "District R2": "الحي R2",
  "Financial and Business District": "الحي المالي والتجاري",
  "City of Arts and Culture": "مدينة الفنون والثقافة",
  "Governmental District": "الحي الحكومي",
  "Misr Mosque": "مسجد مصر",
  "City of Justice": "مدينة العدالة",
  "Adly Mansour": "عدلي منصور",
  "Al-Obour": "العبور",
  "Al-Mostakbal": "المستقبل",
  "Al-Shorouk": "الشروق",
  "New Heliopolis": "هليوبوليس الجديدة",
  Badr: "بدر",
  "Al-Robiky": "الروبيكي",
  "Hadayek Al-Asema": "حدائق العاصمة",
  "Capital Airport": "مطار العاصمة",
  "Arts and Culture": "الفنون والثقافة",
  "Industrial Zone": "المنطقة الصناعية",
  "Knowledge City": "مدينة المعرفة",
  "Cathedral of the Nativity of Christ": "كاتدرائية ميلاد المسيح",
  "Strategic Command": "القيادة الاستراتيجية",
  "International Sports City": "المدينة الرياضية الدولية",
  "Central Capital": "العاصمة المركزية",
};
